apiVersion: v1
kind: Service
metadata:
  name: root-service
  namespace: go-apps
spec:
  selector:
    app: root-app
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: go-apps
spec:
  selector:
    app: api-app
  ports:
  - port: 80
    targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: info-service
  namespace: go-apps
spec:
  selector:
    app: info-app
  ports:
  - port: 80
    targetPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
  namespace: go-apps
spec:
  selector:
    app: login-app
  ports:
  - port: 80
    targetPort: 8083